version: '3'
services:
  mysql:
    image: mariadb:10.5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${DATABASE_USERNAME}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysqlconfig:/etc/mysql/conf.d
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - mysql
    volumes:
      - .:/app/
      - /app/node_modules
    # command: >
    #   sh -c "yarn && yarn migration:run && yarn seed:run && yarn start:dev"
  adminer:
    image: adminer
    restart: always
    ports:
      - 80:80
volumes:
  mysqldata: {}
